app = "legal-diary-backend"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"
  DB_HOST = "pg-1b37a887-chavansahil899-fbbf.h.aivencloud.com"
  DB_PORT = "13584"
  DB_NAME = "defaultdb"
  DB_USER = "avnadmin"
  DB_SSL = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
